services:
  ollama:
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    # config for GPU support(uncomment below if computer support GPU)
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: 1
    #          capabilities: [gpu]

  open-webui:
    build:
      context: .
      args:
        OLLAMA_BASE_URL: 'http://127.0.0.1:11434'
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:${WEBUI_DOCKER_TAG-main}
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      #- 'OPENAI_API_BASE_URLS="https://api.openai.com/v1"'
      #- 'OPENAI_API_KEYS = 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'
      #- 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}